### PR TITLE
Memory coherence mitigation

### PR DESCRIPTION
**Pull request by farfact**
Improve CPU cache miss ratio by aligning x9_inbox atomics to cache line.

### CODE REVIEW

**Comment by df308** [comment]
Why are you padding the structure with 56 bytes? Both the read and write idx are already guaranteed to be in different cache lines.

**Comment by farfact** [comment]
Because the members of struct x9_inbox that immediate follow write_idx would reside in the same cache line as write_idx, thus each time you write to write_idx would invalidate the L1 cache lines of the other CPU core that is reading from it, in practical terms, when one thread is calling x9_load_idx() or x9_header_ptr() it would be hit with a cache miss when another thread increments write_idx.

Instead of explicitly adding the padding, one could align the next adjacent member to X9_CL_SIZE and the compiler would do the padding behind the scenes.

**Comment by df308** [comment]
I think I prefer the later option because it's consistent with what the compiler is already doing between the read_idx and write_idx.

**Comment by df308** [comment]
I have edited the PR and will merge it from https://github.com/df308/x9/pull/3

**Comment by farfact** [comment]
Closing this PR, moved to [#3](https://github.com/df308/x9/pull/3)

**Pull request closed without merging**
